FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src/migration.py ./migration.py

# Le CSV sera monté dans /app/data par docker-compose
CMD ["python", "migration.py"]

